title: Hello, world! I'm William Mburu
description: > # this means to ignore newlines until "baseurl:"
  I have developed interest in data analysis, quantitative research, and using various statistical techniques 
  in order to develop useful solutions to problems I come across. A result driven individual with great communication
  skills that can be a valuable asset to any working team. In search of opportunities that will enable me gain practical 
  experience on the field of Statistics while developing my career path.
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: William Mburu # add your name
author-img: IMG_20210125_214651485.jpg # add your photo
about-author: I am a Financial Analyst. Always famished to keep learning. # add description
social-twitter: # add your Twitter handle
social-github: SirWilliam254 # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: muthee-disqus.com # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
